#40 add action on hover
CodeForPoznan/alinka-website pull request #47
Opened 2020-09-06 17:38 UTC by martabakaj

2020-10-21 20:08 UTC, m-recz requested changes

2020-10-21 20:08 UTC, m-recz commented on assets/scss/_button.scss
> +  }
I would move the transition to the element itself, like this:
``` scss
    .button {
        (...)
        cursor: pointer;
        transition: background-color 300ms;

        &:hover {
            background-color: $lightblue;
        }
```

Like this the transition will occur in both directions. In case of placing the transition inside the :hover pseudoclass, the transition effect is only in one direction, when the hover goes on and not when it goes off.

2020-10-21 20:08 UTC, m-recz commented on assets/scss/_button.scss
> +      transition: background-color 300ms;
Same as above, I would place the transition inside the &--vivid class and not inside the :hover pseudoclass.

2020-10-22 14:51 UTC, martabakaj commented on assets/scss/_button.scss
> +  }
ok, thank you  :)

2020-10-22 14:52 UTC, martabakaj commented on assets/scss/_button.scss
> +      transition: background-color 300ms;
ok , thank you. I change it that like you wrote :)

2020-10-22 18:37 UTC, m-recz approved these changes

2020-10-26 01:01 UTC, merged